[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "muon_sim"
authors = [{name = "zazbone", email = "coczaz@gmail.com"}]
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: MIT License"]
dynamic = ["version", "description"]

dependencies = [
	"numpy >= 1.23",
	"matplotlib >= 3.6",
	"scipy >= 1.9"
]

[project.urls]
Home = "https://github.com/zazbone"
